language: cpp

dist: trusty
sudo: require

matrix:
  include:
    - addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
      env: CXX=g++-6
    - addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.6
          packages:
            - clang-3.6
      env: CXX=clang++-3.6
      after_success: coveralls --exclude doctest.h -t GdwyhgW7dWNP8F2nPJhfml2p89pYt41bR

before_install:
  - pip install --user cpp-coveralls

script:
  - $CXX -v
  - make && make test

