language: cpp

dist: trusty
sudo: require

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-precise-3.9
    packages:
      - g++-6
      - clang-3.9

compiler:
  - clang
  - gcc

before_install:
  - pip install --user cpp-coveralls

script:
  - sudo ln -s /usr/bin/g++-6 /usr/local/bin/g++
  - g++ -v && clang++ -v
  - make && make test

after_success:
  - coveralls --exclude doctest.h -t GdwyhgW7dWNP8F2nPJhfml2p89pYt41bR
