language: cpp

dist: trusty
sudo: false

matrix:
  include:
    - addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
      env: COMPILER=g++-6
    - addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.6
          packages:
            - clang-3.6
      env: COMPILER=clang++-3.6

before_install:
  - pip install --user cpp-coveralls

script:
  - export CXX=$COMPILER
  - $CXX -v
  - if [ "$CXX" == "g++-6" ]; then export TINYCOMPO_FLAGS="-fprofile-arcs -ftest-coverage -g"; fi
  - make && make test

after_success:
  - if [ "$CXX" == "g++-6" ]; then coveralls --exclude doctest.h --exclude test.cpp -t GdwyhgW7dWNP8F2nPJhfml2p89pYt41bR; fi
