language: cpp

dist: trusty
sudo: false

addons:
  apt:
    packages:
      - g++-5
      - libopenmpi-dev
      - openmpi-bin

matrix:
  include:
    - addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
      env:
        - COMPILER=g++-5
        - OMPI_CXX=$COMPILER
    - addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.6
          packages:
            - clang-3.6
      env:
        - COMPILER=clang++-3.6
        - OMPI_CXX=$COMPILER

before_install:
  - pip install --user cpp-coveralls

script:
  - export CXX=$COMPILER
  - $CXX -v
  - mpic++ -v
  - if [ "$CXX" == "g++-5" ]; then export TINYCOMPO_FLAGS="-fprofile-arcs -ftest-coverage -g"; fi
  - make && make test && make test_mpi

after_success:
  - if [ "$CXX" == "g++-5" ]; then coveralls --exclude test --exclude example --exclude test.cpp -t GdwyhgW7dWNP8F2nPJhfml2p89pYt41bR; fi
